
#1. CRIE UM PASTA LOCAL NO SEU COMPUTADOR E INICIALIZE O GIT NESSA PASTA COM GIT INIT;
#2. ADICIONE ARQUIVOS NESSA PASTA E VEJA AS MODIFICAÇÕES COM GIT STATUS;
#3. UTILIZE O GIT ADD E O GIT COMMIT;
#4. CRIE UM NOVO REPOSITÓRIO NO SEU GITHUB;
#5. CONECTE ESSE REPOSITÓRIO REMOTE COM O SEU REPOSITÓRIO LOCAL DO SEU COMPUTADOR E SINCRONIZE-OS;
#6. CRIE UMA NOVA BRANCH E NAVEGUE ENTRE AS BRANCHES
#7. CRIE UM PULL REQUEST NO GITHUB E FAÇA O MERGE;



print("Alteração na branch desenvolvimento")
print("Mais uma alteração nova")